/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_expotec;

import java.awt.*;
import javax.swing.*;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author anerm
 */
public class Carrera extends javax.swing.JFrame {

    /**
     * Creates new form Carrera
     */
    public Carrera() {
        try {
            initComponents();
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        } catch (NullPointerException e) {
            System.out.println("Aviso: No se encontró la imagen, pero el programa continuará.");
        }

        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                redimensionar();
            }
        });

        inyectarNuevoCodigoDinamico();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 234, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(244, 239, 245));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(770, 370));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 109, -1, -1));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(107, 107, 138));
        jLabel13.setText("¡Bienvenido de vuelta!");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(45, 37, 80));
        jLabel14.setText("Estás preparando tu ingreso para la carrera de:");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Tu preparación va al  %");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 106, 1150, 100));

        jPanel2.setBackground(new java.awt.Color(30, 27, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carrera");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 70));

        jPanel6.setBackground(new java.awt.Color(30, 27, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(67, 48));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/Imagen_66x47.png"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 11, 600, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1200, 70));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setText("Tus Módulos de Diagnóstico y Estudio");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Completa las lecciones y evaluaciones preparadas para tu perfil:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jPanel3.setBackground(new java.awt.Color(244, 239, 245));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(208, 197, 228));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 37, 80));
        jLabel2.setText(" Área Específica: ");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel2.setOpaque(true);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 23, -1, -1));

        jProgressBar2.setForeground(new java.awt.Color(107, 107, 138));
        jPanel3.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        jLabel20.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(107, 107, 138));
        jLabel20.setText("Progreso");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(107, 107, 138));
        jLabel22.setText("%");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(107, 107, 138));
        jLabel24.setText("Lógica y Algorítmia");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(107, 107, 138));
        jLabel26.setText("Introducción al pensamiento");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(107, 107, 138));
        jLabel28.setText("estructurado, Resolución de");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel30.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(107, 107, 138));
        jLabel30.setText("problemas y psedocódigo básico.");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 107, 26));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton4.setText("Empezar Módulo");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 330, 280, 280));

        jPanel4.setBackground(new java.awt.Color(244, 239, 245));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(208, 197, 228));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 37, 80));
        jLabel3.setText(" Área Básica: ");
        jLabel3.setToolTipText("");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel3.setOpaque(true);
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(107, 107, 138));
        jLabel11.setText("Matemáticas Universitarias");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(107, 107, 138));
        jLabel15.setText("Aritmética, Álgebra elemental,");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(107, 107, 138));
        jLabel16.setText("Intersecciones de coordenadas.");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(107, 107, 138));
        jLabel17.setText("Funciones polinómicas e");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(107, 107, 138));
        jLabel18.setText("Progreso");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(107, 107, 138));
        jLabel19.setText("%");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jProgressBar1.setForeground(new java.awt.Color(107, 107, 138));
        jPanel4.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        jButton1.setBackground(new java.awt.Color(255, 107, 26));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton1.setText("Empezar Módulo");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, 280));

        jPanel5.setBackground(new java.awt.Color(244, 239, 245));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(196, 184, 232));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 37, 80));
        jLabel4.setText(" Aptitud: ");
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel4.setOpaque(true);
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, -1, -1));

        jProgressBar3.setForeground(new java.awt.Color(107, 107, 138));
        jPanel5.add(jProgressBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(107, 107, 138));
        jLabel21.setText("Progreso");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(107, 107, 138));
        jLabel23.setText("%");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(107, 107, 138));
        jLabel25.setText("Comprensión lectora");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(107, 107, 138));
        jLabel27.setText("Análisis de textos complejos,");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(107, 107, 138));
        jLabel29.setText("razonamiento verbal y diagnóstico");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(107, 107, 138));
        jLabel31.setText("de vocabulario crítico.");
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 107, 26));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton5.setText("Empezar Módulo");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 285, 280));

        jPanel8.setBackground(new java.awt.Color(244, 239, 245));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(208, 197, 228));
        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(45, 37, 80));
        jLabel32.setText(" Aptitud: ");
        jLabel32.setToolTipText("");
        jLabel32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jLabel32.setOpaque(true);
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 22, -1, -1));

        jProgressBar4.setForeground(new java.awt.Color(107, 107, 138));
        jPanel8.add(jProgressBar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        jLabel33.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(107, 107, 138));
        jLabel33.setText("Progreso");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(107, 107, 138));
        jLabel34.setText("%");
        jPanel8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(107, 107, 138));
        jLabel35.setText("Comprensión lectora");
        jPanel8.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(107, 107, 138));
        jLabel36.setText("Análisis de textos complejos,");
        jPanel8.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel37.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(107, 107, 138));
        jLabel37.setText("razonamiento verbal y diagnóstico");
        jPanel8.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel38.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(107, 107, 138));
        jLabel38.setText("de vocabulario crítico.");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 107, 26));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton6.setText("Empezar Módulo");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 285, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void redimensionar() {

        int ancho = getContentPane().getWidth();
        int alto = getContentPane().getHeight();

        // Barra superior
        jPanel2.setBounds(0, 0, ancho, 70);

        // Panel de bienvenida
        jLabel6.setBounds(ancho / 30, alto / 3 - 10, 600, 30);

        // Título
        jLabel7.setBounds(ancho / 30, alto / 3, 600, 85);

        // Cálculo de los módulos
        int margen = 20;
        int espacio = 15;

        int anchoModulo
                = (ancho - (margen * 2) - (espacio * 3))
                / 4;

        int altoModulo = alto / 3;

        int y = alto / 2;

        jPanel4.setBounds(
                margen,
                y,
                anchoModulo,
                altoModulo
        );

        jPanel3.setBounds(
                margen + anchoModulo + espacio,
                y,
                anchoModulo,
                altoModulo
        );

        jPanel8.setBounds(
                margen + (anchoModulo + espacio) * 2,
                y,
                anchoModulo,
                altoModulo
        );

        jPanel5.setBounds(
                margen + (anchoModulo + espacio) * 3,
                y,
                anchoModulo,
                altoModulo
        );

        jPanel6.setBounds(
                0,
                alto - 70,
                ancho,
                90
        );

        jPanel7.setBounds(
                ancho / 40,
                alto / 8,
                ancho - (ancho / 20),
                100
        );
        jLabel8.setBounds(jPanel7.getWidth() - 215, 10, 200, 40);

        int yLinea1 = altoModulo - 250;
        int yLinea2 = altoModulo - 225;
        int yLinea3 = altoModulo - 203;
        int yLinea4 = altoModulo - 179;

        int xTexto = anchoModulo / 8;

// Panel 4 - Área Básica
        jLabel11.setBounds(xTexto, yLinea1, anchoModulo - xTexto - 10, 22);
        jLabel15.setBounds(xTexto, yLinea2, anchoModulo - xTexto - 10, 22);
        jLabel17.setBounds(xTexto, yLinea3, anchoModulo - xTexto - 10, 22);
        jLabel16.setBounds(xTexto, yLinea4, anchoModulo - xTexto - 10, 22);

// Panel 3 - Área Específica
        jLabel24.setBounds(xTexto, yLinea1, anchoModulo - xTexto - 10, 22);
        jLabel26.setBounds(xTexto, yLinea2, anchoModulo - xTexto - 10, 22);
        jLabel28.setBounds(xTexto, yLinea3, anchoModulo - xTexto - 10, 22);
        jLabel30.setBounds(xTexto, yLinea4, anchoModulo - xTexto - 10, 22);

// Panel 5 - Aptitud
        jLabel25.setBounds(xTexto, yLinea1, anchoModulo - xTexto - 10, 22);
        jLabel27.setBounds(xTexto, yLinea2, anchoModulo - xTexto - 10, 22);
        jLabel29.setBounds(xTexto, yLinea3, anchoModulo - xTexto - 10, 22);
        jLabel31.setBounds(xTexto, yLinea4, anchoModulo - xTexto - 10, 22);

// Panel 8 - Aptitud
        jLabel35.setBounds(xTexto, yLinea1, anchoModulo - xTexto - 10, 22);
        jLabel36.setBounds(xTexto, yLinea2, anchoModulo - xTexto - 10, 22);
        jLabel37.setBounds(xTexto, yLinea3, anchoModulo - xTexto - 10, 22);
        jLabel38.setBounds(xTexto, yLinea4, anchoModulo - xTexto - 10, 22);

        int yBarra = altoModulo - 115;
        int yProgreso = altoModulo - 140;

        jProgressBar1.setBounds(45, yBarra, anchoModulo - 70, 16);
        jProgressBar2.setBounds(45, yBarra, anchoModulo - 70, 16);
        jProgressBar3.setBounds(45, yBarra, anchoModulo - 70, 16);
        jProgressBar4.setBounds(45, yBarra, anchoModulo - 70, 16);

        jLabel18.setBounds(35, yProgreso, anchoModulo - 60, 22);
        jLabel19.setBounds(anchoModulo - 50, yProgreso, 40, 22);

        jLabel20.setBounds(35, yProgreso, anchoModulo - 60, 22);
        jLabel22.setBounds(anchoModulo - 50, yProgreso, 40, 22);

        jLabel21.setBounds(35, yProgreso, anchoModulo - 60, 22);
        jLabel23.setBounds(anchoModulo - 50, yProgreso, 40, 22);

        jLabel33.setBounds(35, yProgreso, anchoModulo - 60, 22);
        jLabel34.setBounds(anchoModulo - 50, yProgreso, 40, 22);

        int yBoton = altoModulo - 60;
        jButton1.setBounds(anchoModulo / 2 - 80, yBoton, 160, 50);
        jButton4.setBounds(anchoModulo / 2 - 80, yBoton, 160, 50);
        jButton5.setBounds(anchoModulo / 2 - 80, yBoton, 160, 50);
        jButton6.setBounds(anchoModulo / 2 - 80, yBoton, 160, 50);

        repaint();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carrera().setVisible(true);
            }
        });
    }

    private void inyectarNuevoCodigoDinamico() {
        Font fontLabels = new Font("SansSerif", Font.PLAIN, 20);
        Font fontTitulos = new Font("SansSerif", Font.BOLD, 28);
        Color colorTexto = new Color(107, 107, 138);
        Color colorTitulo = new Color(45, 37, 80);
        Color colorFondoLabel = new Color(196, 184, 232);

        if (jLabel10 != null) {
            try {
                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Imagen_66X47.png")));
                jPanel6.remove(jLabel10);

                jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 15, 20, 0));
            } catch (Exception e) {
                jLabel10.setIcon(null);
            }
        }

        jLabel13.setFont(fontTitulos);
        jLabel6.setFont(fontTitulos);

        // Módulo 3 - Área Específica
        jLabel2.setBackground(colorFondoLabel);
        jLabel2.setForeground(colorTitulo);
        jLabel20.setFont(fontLabels);
        jLabel20.setForeground(colorTexto);
        jLabel22.setFont(new Font("Tahoma", Font.PLAIN, 18));
        jLabel22.setForeground(colorTexto);
        jLabel24.setFont(fontLabels);
        jLabel24.setForeground(colorTexto);
        jLabel26.setFont(fontLabels);
        jLabel26.setForeground(colorTexto);
        jLabel28.setFont(fontLabels);
        jLabel28.setForeground(colorTexto);
        jLabel30.setFont(fontLabels);
        jLabel30.setForeground(colorTexto);
        jLabel30.setText("problemas y psedocódigo básico.");

        // Módulo 4 - Área Básica
        jLabel3.setBackground(colorFondoLabel);
        jLabel3.setForeground(colorTitulo);
        jLabel11.setFont(fontLabels);
        jLabel11.setForeground(colorTexto);
        jLabel15.setFont(fontLabels);
        jLabel15.setForeground(colorTexto);
        jLabel17.setFont(fontLabels);
        jLabel17.setForeground(colorTexto);
        jLabel16.setFont(fontLabels);
        jLabel16.setForeground(colorTexto);
        jLabel18.setFont(fontLabels);
        jLabel18.setForeground(colorTexto);
        jLabel19.setFont(new Font("Tahoma", Font.PLAIN, 18));
        jLabel19.setForeground(colorTexto);

        // Módulo 5 - Aptitud
        jLabel4.setBackground(colorFondoLabel);
        jLabel4.setForeground(colorTitulo);
        jLabel21.setFont(fontLabels);
        jLabel21.setForeground(colorTexto);
        jLabel23.setFont(new Font("Tahoma", Font.PLAIN, 18));
        jLabel23.setForeground(colorTexto);
        jLabel25.setFont(fontLabels);
        jLabel25.setForeground(colorTexto);
        jLabel27.setFont(fontLabels);
        jLabel27.setForeground(colorTexto);
        jLabel29.setFont(fontLabels);
        jLabel29.setForeground(colorTexto);
        jLabel31.setFont(fontLabels);
        jLabel31.setForeground(colorTexto);
        
        for (java.awt.event.ActionListener al : jButton1.getActionListeners()) {
            jButton1.removeActionListener(al);
        }
        jButton1.addActionListener(evt -> {
            Modulo ventanaModulo = new Modulo();
            ventanaModulo.setExtendedState(javax.swing.JFrame.NORMAL);
            ventanaModulo.setLocationRelativeTo(null);
            ventanaModulo.setVisible(true);
            ventanaModulo.toFront();
            ventanaModulo.requestFocus();
            this.dispose();
        });

        Color colorBoton = new Color(255, 107, 26);
        jButton1.setBackground(colorBoton);
        jButton1.setForeground(Color.white);
        jButton4.setBackground(colorBoton);
        jButton4.setForeground(Color.white);
        jButton5.setBackground(colorBoton);
        jButton5.setForeground(Color.white);

        jPanel1.revalidate();
        jPanel1.repaint();
        jPanel2.revalidate();
        jPanel2.repaint();
        jPanel3.revalidate();
        jPanel3.repaint();
        jPanel4.revalidate();
        jPanel4.repaint();
        jPanel5.revalidate();
        jPanel5.repaint();
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    // End of variables declaration                   
}
