/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_expotec;

import Clases.Conexion;
import interfaz_expotec.Prueba_Vocacional;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import interfaz_expotec.CRUD;

/**
 *
 * @author anerm
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        txtnombre.setText("Nombre de Usuario");
        txtEmail.setText("Usuario o correo");
        txtpassword_hash.setText("Contraseña");
        this.requestFocusInWindow();
        txtpassword_hash.setEchoChar((char) 0);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setLayout(null);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                redimensionar();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtpassword_hash = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 234, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 560));

        jPanel7.setBackground(new java.awt.Color(244, 239, 245));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(770, 370));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 37, 80));
        jLabel6.setText("Crear Cuenta");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 107, 26));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton1.setText("Registrarse");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 160, 50));
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 109, -1, -1));

        txtEmail.setBackground(new java.awt.Color(255, 107, 26));
        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 107, 26), 8, true));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel7.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 410, 50));

        txtnombre.setBackground(new java.awt.Color(255, 107, 26));
        txtnombre.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(255, 255, 255));
        txtnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 107, 26), 8, true));
        txtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombreFocusLost(evt);
            }
        });
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel7.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 410, 50));

        txtpassword_hash.setBackground(new java.awt.Color(255, 107, 26));
        txtpassword_hash.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtpassword_hash.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword_hash.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword_hash.setBorder(null);
        txtpassword_hash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassword_hashFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpassword_hashFocusLost(evt);
            }
        });
        jPanel7.add(txtpassword_hash, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 410, 50));

        jPanel2.setBackground(new java.awt.Color(30, 27, 46));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear Cuenta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(1066, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(30, 27, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(67, 48));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/imagen_66x47.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(562, 562, 562)
                    .addComponent(jLabel10)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabel10)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                                                

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    String nombre = txtnombre.getText().trim();
    String email = txtEmail.getText().trim();
    String password_hash = new String(txtpassword_hash.getPassword());
    
    // 1. Validar campos vacíos
    if (nombre.isEmpty() || nombre.equals("Nombre de Usuario") ||
        email.isEmpty() || email.equals("Usuario o correo") ||
        password_hash.isEmpty() || password_hash.equals("Contraseña")) {
        
        JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos obligatorios antes de continuar.");
        return; 
    }

    // 2. Validar sintaxis del correo
    if (!email.matches("^[A-Za-z0-9+_.-]+@(.+)$")) {
        JOptionPane.showMessageDialog(null, "El correo electrónico ingresado no tiene un formato válido.", "Formato Inválido", JOptionPane.ERROR_MESSAGE);
        return;
    }

    JOptionPane.showMessageDialog(null, "Enviando código de verificación a: " + email + "\nPor favor espere un momento", "Verificando Correo Electrónico", JOptionPane.INFORMATION_MESSAGE);
    
    Clases.ServicioCorreo servicioMail = new Clases.ServicioCorreo();
    String codigoGenerado = servicioMail.generarCodigo();
    
    boolean enviado = servicioMail.enviarCodigoVerificacion(email, codigoGenerado);
    
    if (!enviado) {
        JOptionPane.showMessageDialog(null, "No se pudo enviar el correo electrónico. Verifique su conexión o que el correo emisor esté bien configurado.", "Error de Envío", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String codigoUsuario = JOptionPane.showInputDialog(null, "Hemos enviado un código de 6 dígitos a tu correo.\nIngrésalo aquí para verificar tu cuenta:", "Verificación de Cuenta", JOptionPane.QUESTION_MESSAGE);
    
    if (codigoUsuario == null) {
        JOptionPane.showMessageDialog(null, "Registro cancelado por el usuario.");
        return;
    }

    if (codigoUsuario.trim().equals(codigoGenerado)) {
        Clases.Conexion co = new Clases.Conexion();
        int respuesta = co.usuarios(nombre, email, password_hash);
        
        if (respuesta == 1) {
            JOptionPane.showMessageDialog(null, "¡Cuenta verificada y registrada correctamente!");
            
            String emailMinusculas = email.toLowerCase();
            if (emailMinusculas.contains("admin") || emailMinusculas.contains("mod")) {
CRUD panelCrud = new CRUD(nombre, email); 
panelCrud.setVisible(true);
            } else {
                Prueba_Vocacional pruebaVocacional = new Prueba_Vocacional();
                pruebaVocacional.setVisible(true);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error al escribir en la Base de Datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "El código introducido es incorrecto. Validación fallida.", "Código Erróneo", JOptionPane.ERROR_MESSAGE);
    }
}                                                   

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {                                                                                    
        // TODO add your handling code here:
    }                                                                                  

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {                                                                                  
        // TODO add your handling code here:
    }                                                                                

    private void txtpassword_hashFocusGained(java.awt.event.FocusEvent evt) {                                                                                          
        String pass = new String(txtpassword_hash.getPassword());
        if (pass.equals("Contraseña")) {
            txtpassword_hash.setText("");
            txtpassword_hash.setEchoChar('•');
        }
    }                                                                                        

    private void txtpassword_hashFocusLost(java.awt.event.FocusEvent evt) {                                                                                      
        String pass = new String(txtpassword_hash.getPassword());
        if (pass.isEmpty()) {
            txtpassword_hash.setText("Contraseña");
            txtpassword_hash.setEchoChar((char) 0);
        }    
    }                                                                                    

    private void txtnombreFocusGained(java.awt.event.FocusEvent evt) {                                                                            
        if (txtnombre.getText().equals("Nombre de Usuario")) {
            txtnombre.setText("");
        }
    }                                                                          

    private void txtnombreFocusLost(java.awt.event.FocusEvent evt) {                                    
        if (txtnombre.getText().isEmpty()) {
            txtnombre.setText("Nombre de Usuario");
        }
    }                                                                       

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {                                                                          
        if (txtEmail.getText().equals("Usuario o correo")) {
            txtEmail.setText("");
        }
    }                                                                        

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {                                                                      
        if (txtEmail.getText().isEmpty()) {
            txtEmail.setText("Usuario o correo");
        }
    }                                                                    

    private void redimensionar() {
        int ancho = getContentPane().getWidth();
        int alto = getContentPane().getHeight();

        jPanel1.setBounds(0, 0, ancho, alto);
        jPanel1.setLayout(null);

        jPanel2.setBounds(0, 0, ancho, 70);
        jPanel6.setBounds(0, alto - 70, ancho, 70);

        int anchoPanel = 800;
        int altoPanel = 710;
        int xPanel = (ancho - anchoPanel) / 2;
        int yPanel = (alto - altoPanel) / 2;

        jPanel7.setBounds(xPanel, yPanel, anchoPanel, altoPanel);
        jPanel7.setLayout(null);

        int cx = anchoPanel / 2;
        int anchoInput = 410;
        int xInput = (anchoPanel - anchoInput) / 2;

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBounds(0, 40, anchoPanel, 50);

        txtnombre.setBounds(xInput, 130, anchoInput, 50);  
        txtEmail.setBounds(xInput, 210, anchoInput, 50);  
        txtpassword_hash.setBounds(xInput, 290, anchoInput, 50);  

        jButton1.setBounds(cx - 80, 380, 160, 50);

        int bajada = 100; 

        jLabel6.setBounds(0, 40 + bajada, anchoPanel, 50);
        txtnombre.setBounds(xInput, 130 + bajada, anchoInput, 50);
        txtEmail.setBounds(xInput, 210 + bajada, anchoInput, 50);
        txtpassword_hash.setBounds(xInput, 290 + bajada, anchoInput, 50);
        jButton1.setBounds(cx - 80, 380 + bajada, 160, 50);

        jPanel7.revalidate();
        jPanel7.repaint();
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JPasswordField txtpassword_hash;
    // End of variables declaration                   
}