/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz_expotec;
import Clases.Conexion;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.Vector;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Computacion
 */
public class CRUD extends javax.swing.JFrame {
    
    private String usuarioRol;           
    private String usuarioPasswordReal;  
    
    // Instancia global de tu clase Conexion
    private Conexion conexionBD;
    
    private javax.swing.JComboBox<String> comboTablas; 
    private javax.swing.JPanel panelCRUD;
    private TableRowSorter<DefaultTableModel> sorter;
    
    // Consola SQL para Administradores
    private javax.swing.JTextArea txtConsoleSQL;

    // Caché para la función de Deshacer
    private Vector datosOriginales;
    private Vector columnasOriginales;


    public CRUD(String rol, String passwordReal) {
        this.usuarioRol = rol;
        this.usuarioPasswordReal = passwordReal;
        
        // Inicializamos tu clase del paquete Clases
        this.conexionBD = new Conexion();
        
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);

        ConfigurarComponentesDinamicos();

        addComponentListener(
                new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                redimensionar();
            }
        }
        );

        redimensionar();
        
        // Carga inicial de la primera tabla utilizando tu conexión
        cargarDatosTabla(comboTablas.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 234, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(970, 560));

        jPanel7.setBackground(new java.awt.Color(244, 239, 245));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(770, 370));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 37, 80));
        jLabel6.setText("Listado de Usuarios");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 6, -1, -1));
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 109, -1, -1));

        jPanel2.setBackground(new java.awt.Color(30, 27, 46));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(30, 27, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(67, 48));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(1184, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(244, 239, 245));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel3.setPreferredSize(new java.awt.Dimension(245, 355));

        jTextField1.setForeground(new java.awt.Color(45, 37, 80));
        jTextField1.setText("       ");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 107, 26));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton1.setText("Agregar");

        jButton2.setBackground(new java.awt.Color(255, 107, 26));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/basura.png"))); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 107, 26));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/actualizar.png"))); // NOI18N
        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 107, 26));
        jButton4.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton4.setText("Mostrar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(7, 7, 7)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18))
        );

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nombre", "Email", "Cotraseña", "Rol", "Estado", "Carrera_Administrador", "Fecha_Registro"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(244, 239, 245));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada != -1) {
        // 1. Extraemos los strings de la fila seleccionada en jTable1
        String id = jTable1.getValueAt(filaSeleccionada, 0).toString();
        String nombre = jTable1.getValueAt(filaSeleccionada, 1).toString();
        String email = jTable1.getValueAt(filaSeleccionada, 2).toString();
        jTextField1.setText(nombre); 
        
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                      
    int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un usuario de la tabla primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int idUsuario = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
    
    String nuevoNombre = jTextField1.getText().trim();

    if (nuevoNombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El campo de texto no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    String sql = "UPDATE usuarios SET nombre = ? WHERE id_usuario = ?";

    try {
        Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Qode_db", "root", "admin"); 
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        
        ps.setString(1, nuevoNombre);
        ps.setInt(2, idUsuario);

        int resultado = ps.executeUpdate();

        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "¡Registro actualizado con éxito!");
            
            cargarDatosTabla(comboTablas.getSelectedItem().toString());
            
            jTextField1.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar el registro en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        ps.close();
        con.close();

    } catch (java.sql.SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error SQL al actualizar: " + ex.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int filaSeleccionada = jTable1.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione el usuario que desea eliminar en la tabla.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String idUsuario = jTable1.getValueAt(filaSeleccionada, 0).toString();
    String nombreUsuario = jTable1.getValueAt(filaSeleccionada, 1).toString();

    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Está seguro de que desea eliminar al usuario '" + nombreUsuario + "' (ID: " + idUsuario + ")?", 
        "Confirmar Eliminación", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        
        String sql = "DELETE FROM usuarios WHERE id_usuario = ?";

        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Qode_db", "root", "admin"); 
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setInt(1, Integer.parseInt(idUsuario));

            int resultado = ps.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "¡Usuario eliminado con éxito!");
                
                cargarDatosTabla(comboTablas.getSelectedItem().toString());
                
                jTextField1.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el registro.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            ps.close();
            con.close();

        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error SQL al intentar eliminar: " + ex.getMessage(), "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ConfigurarComponentesDinamicos() {
        jPanel3.setLayout(null);

        String[] tablasBD = { 
            "usuarios", "carreras", "cursos", "modulos", "evaluaciones", 
            "materiales", "preguntas", "opciones", "figura_espacios", 
            "intentos", "evaluacion_pregunta" 
        };
        
        comboTablas = new javax.swing.JComboBox<>(tablasBD);
        comboTablas.setFont(new Font("Arial", Font.BOLD, 14));
        comboTablas.setBackground(Color.WHITE);
        jPanel3.add(comboTablas);

        comboTablas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cargarDatosTabla(comboTablas.getSelectedItem().toString());
            }
        });

        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                filtrarDatos(jTextField1.getText());
            }
        });

        panelCRUD = new JPanel(new GridLayout(1, 1));
        panelCRUD.setBackground(new java.awt.Color(244, 239, 245));
        
        txtConsoleSQL = new JTextArea("SCRIPT SQL (solo rol administrador)");
        txtConsoleSQL.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane scrollConsole = new JScrollPane(txtConsoleSQL);
        panelCRUD.add(scrollConsole);
        
        jPanel3.add(panelCRUD);

        if (!"admin".equalsIgnoreCase(usuarioRol)) {
            txtConsoleSQL.setText("CONSOLA BLOQUEADA: NO TIENE ACCESO A ESTE APARTADO.");
            txtConsoleSQL.setEnabled(false);
            jButton4.setEnabled(false);
        }
    }
    
    private void redimensionar() {
        int ancho = getContentPane().getWidth();
        int alto = getContentPane().getHeight();

        jPanel1.setLayout(null);
        jPanel1.setBounds(0, 0, ancho, alto);
        jPanel2.setBounds(0, 0, ancho, 70);
        jPanel7.setBounds(120, 120, ancho - 200, 80);
        jPanel7.setLayout(null);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBounds(0, 0, jPanel7.getWidth(), jPanel7.getHeight());

        int panelIzq = ancho / 5;
        if (panelIzq < 340) panelIzq = 340;

        jPanel3.setBounds(40, 240, panelIzq, alto - 360);
        jScrollPane1.setBounds(panelIzq + 80, 240, ancho - panelIzq - 120, alto - 360);
        jPanel6.setBounds(0, alto - 90, ancho, 90);

       if (comboTablas != null) {
        comboTablas.setBounds(20, 20, panelIzq - 40, 30);
        jTextField1.setBounds(20, 70, panelIzq - 40, 30);
        jButton1.setBounds(20, 120, panelIzq - 40, 35); 
        jButton2.setBounds(20, 170, panelIzq - 40, 35); 
        jButton3.setBounds(20, 220, panelIzq - 40, 35); 
        jButton4.setBounds(20, 270, panelIzq - 40, 35); 
    }

    if (panelCRUD != null) {
        panelCRUD.setBounds(
                20, 
                320,                      
                jPanel3.getWidth() - 40,   
                120                       
        );
    }

        repaint();
        revalidate();
    }
    
    private void cargarDatosTabla(String nombreTabla) {
        if ("usuarios".equalsIgnoreCase(nombreTabla) && "coordinator".equalsIgnoreCase(usuarioRol)) {
            JOptionPane.showMessageDialog(this, "Acceso de Moderador: Visualizando personal de menor jerarquía.");
        }

        DefaultTableModel modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0; 
            }
        };

        String queryBase = "SELECT * FROM " + nombreTabla;
        if ("usuarios".equalsIgnoreCase(nombreTabla) && "coordinator".equalsIgnoreCase(usuarioRol)) {
            queryBase += " WHERE rol != 'admin'"; // Los moderadores no ven a los administradores
        }

        // REUTILIZACIÓN DE TU CONEXIÓN ACTIVA POR MEDIO DEL GETTER
        try (Connection con = conexionBD.getConnection();
             Statement stmt = con.createStatement();
             ResultSet rs = stmt.executeQuery(queryBase)) {

            ResultSetMetaData metaData = rs.getMetaData();
            int columnasCount = metaData.getColumnCount();

            for (int i = 1; i <= columnasCount; i++) {
                modelo.addColumn(metaData.getColumnName(i));
            }

            while (rs.next()) {
                Object[] fila = new Object[columnasCount];
                for (int i = 1; i <= columnasCount; i++) {
                    fila[i - 1] = rs.getObject(i);
                }
                modelo.addRow(fila);
            }

            jTable1.setModel(modelo);
            sorter = new TableRowSorter<>(modelo);
            jTable1.setRowSorter(sorter);

            datosOriginales = (Vector) modelo.getDataVector().clone();
            columnasOriginales = new Vector();
            for (int i = 1; i <= columnasCount; i++) {
                columnasOriginales.add(metaData.getColumnName(i));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error de enlace en Qode_db:\n" + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void filtrarDatos(String texto) {
        if (sorter != null) {
            if (texto.trim().length() == 0) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
            }
        }
    }
    
    private void restaurarDatosOriginales() {
        if (datosOriginales != null && columnasOriginales != null) {
            DefaultTableModel modeloOriginal = new DefaultTableModel((Vector) datosOriginales.clone(), (Vector) columnasOriginales.clone());
            jTable1.setModel(modeloOriginal);
            sorter = new TableRowSorter<>(modeloOriginal);
            jTable1.setRowSorter(sorter);
            jTextField1.setText("");
            JOptionPane.showMessageDialog(this, "Sincronización visual reestablecida.");
        }
    }
    
    private void ejecutarActualizacion() {
        int filaSel = jTable1.getSelectedRow();
        int colSel = jTable1.getSelectedColumn();

        if (filaSel == -1 || colSel == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione la celda exacta a editar.");
            return;
        }

        int filaModelo = jTable1.convertRowIndexToModel(filaSel);
        String tablaActiva = comboTablas.getSelectedItem().toString();
        String campoId = jTable1.getModel().getColumnName(0);
        String campoAModificar = jTable1.getModel().getColumnName(colSel);
        
        Object valorId = jTable1.getModel().getValueAt(filaModelo, 0);
        Object nuevoValor = jTable1.getModel().getValueAt(filaModelo, colSel);

        if ("usuarios".equalsIgnoreCase(tablaActiva) && "rol".equalsIgnoreCase(campoAModificar) && !"admin".equalsIgnoreCase(usuarioRol)) {
            JOptionPane.showMessageDialog(this, "Denegado: No cuenta con privilegios para alterar roles.", "Seguridad", JOptionPane.ERROR_MESSAGE);
            cargarDatosTabla(tablaActiva);
            return;
        }

        String query = "UPDATE " + tablaActiva + " SET " + campoAModificar + " = ? WHERE " + campoId + " = ?";

        try (Connection con = conexionBD.getConnection();
             PreparedStatement pstm = con.prepareStatement(query)) {
            
            pstm.setObject(1, nuevoValor);
            pstm.setObject(2, valorId);
            
            if (pstm.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "¡Modificación guardada con éxito!");
                cargarDatosTabla(tablaActiva);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Fallo al procesar actualización:\n" + ex.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void ejecutarEliminacion() {
        int filaSel = jTable1.getSelectedRow();
        if (filaSel == -1) {
            JOptionPane.showMessageDialog(this, "Haga clic en el registro a eliminar.");
            return;
        }

        int filaModelo = jTable1.convertRowIndexToModel(filaSel);
        String tablaActiva = comboTablas.getSelectedItem().toString();
        String campoId = jTable1.getModel().getColumnName(0);
        Object valorId = jTable1.getModel().getValueAt(filaModelo, 0);

        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Eliminar el registro ID " + valorId + " de la tabla " + tablaActiva + "?", 
                "Alerta", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            String query = "DELETE FROM " + tablaActiva + " WHERE " + campoId + " = ?";
            try (Connection con = conexionBD.getConnection();
                 PreparedStatement pstm = con.prepareStatement(query)) {
                
                pstm.setObject(1, valorId);
                pstm.executeUpdate();
                
                JOptionPane.showMessageDialog(this, "Registro purgado.");
                cargarDatosTabla(tablaActiva);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error de restricción transaccional (FK activa):\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void ejecutarInyeccionSQL() {
        if (!"admin".equalsIgnoreCase(usuarioRol)) return;

        String scriptSQL = txtConsoleSQL.getText().trim();
        if (scriptSQL.isEmpty() || scriptSQL.startsWith("/*")) {
            JOptionPane.showMessageDialog(this, "Escriba un comando ejecutable.");
            return;
        }

        JPanel panelVerificador = new JPanel(new GridLayout(2, 1, 5, 5));
        JLabel lblAlerta = new JLabel("Advertencia: Operación directa en la DB. Confirme su contraseña para continuar:");
        JPasswordField txtConfirmPass = new JPasswordField();
        panelVerificador.add(lblAlerta);
        panelVerificador.add(txtConfirmPass);

        int confirmacion = JOptionPane.showConfirmDialog(this, panelVerificador, 
                "Consola Administrativa", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (confirmacion == JOptionPane.OK_OPTION) {
            String passIngresada = new String(txtConfirmPass.getPassword());
            
            if (passIngresada.equals(usuarioPasswordReal)) {
                try (Connection con = conexionBD.getConnection();
                     Statement stmt = con.createStatement()) {
                    
                    boolean devuelveResultSet = stmt.execute(scriptSQL);
                    
                    if (devuelveResultSet) {
                        ResultSet rs = stmt.getResultSet();
                        DefaultTableModel modeloCustom = new DefaultTableModel();
                        ResultSetMetaData md = rs.getMetaData();
                        int columnasCount = md.getColumnCount();
                        
                        for (int i = 1; i <= columnasCount; i++) modeloCustom.addColumn(md.getColumnName(i));
                        while (rs.next()) {
                            Object[] fila = new Object[columnasCount];
                            for (int i = 1; i <= columnasCount; i++) fila[i - 1] = rs.getObject(i);
                            modeloCustom.addRow(fila);
                        }
                        jTable1.setModel(modeloCustom);
                        JOptionPane.showMessageDialog(this, "Query procesado. Visualice los resultados en la cuadrícula.");
                    } else {
                        int registrosAfectados = stmt.getUpdateCount();
                        JOptionPane.showMessageDialog(this, "Script ejecutado. Filas de entidad modificadas con éxito: " + registrosAfectados);
                        cargarDatosTabla(comboTablas.getSelectedItem().toString());
                    }
                    
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Fallo de sintaxis SQL:\n" + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Contraseña errónea. Ejecución cancelada.", "Acción no autorizada", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new CRUD("admin", "admin").setVisible(true); 
    }
});
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
