/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz_expotec;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;


/**
 *
 * @author anerm
 */
public class Selección_Carrera extends javax.swing.JFrame {

    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JPanel panelCarreras;
    private Map<String, String[]> datosCarreras;

    private final Color GRIS_CELDA = new Color(215, 215, 215);
    private final Color MORADO_CELDA = new Color(54, 25, 60);

    public Selección_Carrera() {
        initComponents();
        inicializarDatos();
        configurarComponentesDinamicos();
        actualizarCuadranteCarreras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 234, 248));
        jPanel1.setPreferredSize(new java.awt.Dimension(969, 553));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 27, 46));

        jLabel1.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        jPanel6.setBackground(new java.awt.Color(30, 27, 46));
        jPanel6.setPreferredSize(new java.awt.Dimension(67, 48));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/imagen_66x47.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(562, 562, 562)
                    .addComponent(jLabel10)
                    .addContainerGap(562, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabel10)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1190, 70));

        jButton1.setBackground(new java.awt.Color(255, 107, 26));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz_expotec/Recursos/flecha-correcta.png"))); // NOI18N
        jButton1.setText("Confirmar Carrera");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 570, 160, 50));

        jPanel7.setBackground(new java.awt.Color(244, 239, 245));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel7.setPreferredSize(new java.awt.Dimension(765, 370));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 37, 80));
        jLabel6.setText("¿Qué carrera deseas elegir?");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Selecciona el área y la carrera universitaria que quieras empezar a preparar:");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 37, 80));
        jLabel8.setText("Carreras:");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 118, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 37, 80));
        jLabel11.setText("Filtrar por Área de estudio:");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 106, 940, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Carrera carrera = new Carrera();
        carrera.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selección_Carrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selección_Carrera().setVisible(true);
            }
        });
    }

    private void configurarComponentesDinamicos() {
        jPanel7.setLayout(null);

        String[] categorias = {"Humanidades", "Económicas", "Ingenierías", "Salud", "Educación"};
        comboFiltro = new javax.swing.JComboBox<>(categorias);
        comboFiltro.setFont(new Font("Arial", Font.PLAIN, 14));
        comboFiltro.setBackground(Color.WHITE);

        comboFiltro.setBounds(60, 145, 585, 35);

        jPanel7.add(comboFiltro, 0);

        panelCarreras = new javax.swing.JPanel(new GridLayout(2, 2, 10, 10));
        panelCarreras.setBackground(new java.awt.Color(244, 239, 245));

        panelCarreras.setBounds(60, 265, 585, 130);

        jPanel7.add(panelCarreras, 0);

        comboFiltro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String opcion
                        = comboFiltro.getSelectedItem().toString();

                System.out.println(opcion);

            }
        });

        jPanel7.removeAll();

        jPanel7.add(jLabel6);
        jPanel7.add(jLabel7);
        jPanel7.add(jLabel8);
        jPanel7.add(jLabel11);

        jPanel7.add(comboFiltro);
        jPanel7.add(panelCarreras);

        jPanel7.revalidate();
        jPanel7.repaint();
    }

    private void inicializarDatos() {
        datosCarreras = new HashMap<>();
        datosCarreras.put("Humanidades", new String[]{"Filosofía", "Letras Clásicas", "Historia"});
        datosCarreras.put("Económicas", new String[]{"Administración de Empresas", "Economía", "Contaduría Pública"});
        datosCarreras.put("Ingenierías", new String[]{"Ingeniería en Sistemas", "Ingeniería Civil", "Ingeniería Industrial"});
        datosCarreras.put("Salud", new String[]{"Medicina General", "Enfermería", "Nutrición"});
        datosCarreras.put("Educación", new String[]{"Pedagogía", "Educación Primaria", "Psicopedagogía"});
    }

    private void actualizarCuadranteCarreras() {
        if (panelCarreras == null) {
            return;
        }

        panelCarreras.removeAll();

        if (comboFiltro.getSelectedItem() == null) {
            return;
        }

        String seleccion = (String) comboFiltro.getSelectedItem();
        String[] carreras = datosCarreras.get(seleccion);

        if (carreras != null) {
            for (int i = 0; i < 4; i++) {
                JPanel celda = new JPanel(new BorderLayout());

                if (i == 0 || i == 1) {
                    celda.setBackground(GRIS_CELDA);
                } else {
                    celda.setBackground(MORADO_CELDA);
                }

                if (i < carreras.length) {
                    JLabel lblNombreCarrera = new JLabel(carreras[i], SwingConstants.CENTER);
                    lblNombreCarrera.setFont(new Font("SansSerif", Font.BOLD, 13));

                    if (celda.getBackground().equals(MORADO_CELDA)) {
                        lblNombreCarrera.setForeground(Color.WHITE);
                    } else {
                        lblNombreCarrera.setForeground(new Color(45, 37, 80));
                    }
                    celda.add(lblNombreCarrera, BorderLayout.CENTER);
                } else {
                    celda.add(new JLabel(""), BorderLayout.CENTER);
                }

                panelCarreras.add(celda);
            }
        }

        panelCarreras.revalidate();
        panelCarreras.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
